/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package block_3;

import java.io.IOException;
import com.github.dtmo.jfiglet.FigFontResources;
import com.github.dtmo.jfiglet.FigletRenderer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        FigletRenderer figletRenderer;
        try {
            figletRenderer = new FigletRenderer(FigFontResources.loadFigFontResource(FigFontResources.LEAN_FLF));
            System.out.println(figletRenderer.renderText("DevOpsIsCool"));
        } catch (IOException e) { 
            // TODO Auto-generated catch block 
            e.printStackTrace(); 
        } 
    } 
}
